path:
  home: runtime/elasticsearch

transport:
  type: mock-socket-network

cluster:
  name: escluster

http:
  enabled: true
node:
  name: alien
network:
  host: 0.0.0.0


# # Search guard SSL configuration

# # Activate client authentication, it means that http client will have to present certificate in order to query elasticsearch rest api
# searchguard.ssl.http.clientauth_mode: REQUIRE

# # If openssl available on the machine, will it be used to manage ssl of the http rest endpoint
# searchguard.ssl.http.enable_openssl_if_available: false

# # Use ssl for http rest endpoint ?
# searchguard.ssl.http.enabled: true

# # The private key for http rest endpoint (relative path to path.conf key)
# searchguard.ssl.http.keystore_filepath: client-keystore.jks

# # Certificate for http rest endpoint (relative path to path.conf key)
# searchguard.ssl.http.truststore_filepath: server-truststore.jks

# # If openssl available on the machine, will it be used to manage ssl of the transport communication between elasticsearch nodes
# searchguard.ssl.transport.enable_openssl_if_available: false

# # Use ssl for transport communication between elasticsearch nodes
# searchguard.ssl.transport.enabled: true

# # Check host name of presented ssl certificates
# searchguard.ssl.transport.enforce_hostname_verification: false

# # Try to resolve host name
# searchguard.ssl.transport.resolve_hostname: false

# # The private key for transport communication (relative path to path.conf key)
# searchguard.ssl.transport.keystore_filepath: client-keystore.jks

# # Certificate for transport communication (relative path to path.conf key)
# searchguard.ssl.transport.truststore_filepath: server-truststore.jks